lesson_12/urls.py
from django.contrib import admin
from django.urls import path, include

from market import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('market/', include('market.urls')),
]

market/urls.py
from django.urls import path

from market import views

app_name = 'market'

urlpatterns = [
    path('', views.list, name='list'),
    path('<int:item_id>/', views.item, name='item')
]

market/models.py
from django.db import models


class Brand(models.Model):
    name = models.CharField(max_length=50)
    rating = models.FloatField(max_length=5)

    def __str__(self):
        return f'{self.id}-{self.name}({self.rating})'


class Wallpaper(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    price = models.FloatField(null=True, blank=True)
    available = models.BooleanField(default=False)
    quantity = models.IntegerField(default=0)
    description = models.TextField()

    def __str__(self):
        return f'{self.brand} - {self.name}'

market/views.py
from django.http import HttpResponse
from django.shortcuts import render

from market.models import Wallpaper


def list(request):
    wallpapers = Wallpaper.objects.all()
    return render(request,
                  'market/wallpapers.html',
                  context={'wallpapers': wallpapers})


def item(request, item_id):
    wallpaper = Wallpaper.objects.get(pk=item_id)
    return render(request,
                  'market/wallpaper.html',
                  context={'wallpaper': wallpaper})

market/templates/market/wallpaper.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wallpeper</title>
</head>
<body>
<a href="{% url 'market:list' %}"><- Return</a>

<h1>Name: {{ wallpaper.name }}</h1>
<h2>Brand: {{ wallpaper.brand.name }}</h2>
<h3>Price: {{ wallpaper.price }}</h3>
</body>
</html>

market/templates/market/wallpapers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wallpepers</title>
</head>
<body>
{% for wallpaper in wallpapers %}
<a href="{% url 'market:item' item_id=wallpaper.id %}">{{ wallpaper }}</a>
{% endfor %}
</body>
</html>